apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-pulse-guard-config
  namespace: payment-pulse-guard
data:
  kafka.bootstrap.servers: "kafka-broker:9092"
  redis.host: "redis-master"
  redis.port: "6379"
