server:
  port: 8084

spring:
  application:
    name: case-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/fraudaml}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
